# Generated by Django 5.0.6 on 2024-08-22 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="user",
        ),
    ]
