# Generated by Django 2.2.28 on 2024-07-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20240710_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientimage',
            old_name='upload_date',
            new_name='uploaded_at',
        ),
    ]
