# Generated by Django 5.0.7 on 2024-08-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_patient_diagnosis_result_patient_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="risk_level",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="patient",
            name="treatment_progress",
            field=models.IntegerField(default=0),
        ),
    ]
