# Generated by Django 5.0.6 on 2024-07-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_hospital_patient_alter_patientimage_id_mriimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mriimage',
            name='image_path',
        ),
        migrations.AddField(
            model_name='mriimage',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
