# Generated by Django 5.0.6 on 2024-07-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_remove_mriimage_image_path_mriimage_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PatientImage",
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="default_name", max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="userID",
            field=models.CharField(
                default="default_userID", max_length=50, unique=True
            ),
        ),
    ]
