# Generated by Django 5.0.6 on 2024-07-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_delete_patientimage_remove_user_username_user_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="userID",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
